[app]
runMode = "dev"
name = "webapp"
port = 8080

logProvider = "file"
logPath = "."
logRotate = true
logRotateType = "day"
logLimit = "100MB"

[session]
enable = false
provider = "file"

[mysql]
host="localhost"
port=3306
user="jason"
db="fenda"
password="jason"

[redis]
host="localhost"
port= 6379
db = 0