# app
[app]
runMode = "dev"
name = "webapp"
sessionEnable = true
sessionProvider = "file"
logProvider = "file"
logRotate = true
logLimit = "100M"

[mysql]
host="localhost"
port=3306
user="root"
db="fenda"
password=""

[redis]
host="localhost"
port=6379
db = 0